In [1]:
import pandas as pd
#load data from csv and print to confirm import
df = pd.read_csv (r'C:\Users\nflfa\Desktop\Git\ControlProject\RawData\RawData.csv')
print (df)

      Index    XMEAS1       XMEAS2       XMEAS3    XMEAS4     XMEAS5  \
0         1  0.271033  3649.739415  4451.320791  9.223142  32.392900
1         2  0.270826  3653.341885  4488.640140  9.211980  32.501953
2         3  0.270474  3688.113265  4432.832766  9.235690  32.402838
3         4  0.272127  3651.680041  4459.268940  9.192009  31.876790
4         5  0.270939  3636.329271  4460.409756  9.277992  32.424754
...     ...       ...          ...          ...       ...        ...
1990   1991 -0.001158  3744.190299  4863.374473  8.792891  24.901362
1991   1992 -0.001147  3798.451896  4864.787808  8.814539  24.783557
1992   1993 -0.000370  3774.038558  4891.309364  8.659021  24.805757
1993   1994 -0.000925  3812.197101  4909.631048  8.724842  24.877275
1994   1995 -0.000317  3761.939300  4935.966769  8.746042  24.470426

         XMEAS6       XMEAS7     XMEAS8      XMEAS9  ...        XMV3  \
0     47.559754  2798.975799  64.995825  122.898796  ...   26.662173
1     47.374855  2800.296214  65.091251  122.877519  ...   26.689544
2     47.817088  2802.647777  64.812363  122.916165  ...   26.705507
3     47.869249  2803.693084  64.205417  122.892493  ...   26.768653
4     47.509322  2804.787223  64.598623  122.890514  ...   26.396773
...         ...          ...        ...         ...  ...         ...
1990  40.390117  2903.201084  66.243082  122.882878  ...  100.000000
1991  40.401312  2911.912112  68.055534  122.881328  ...  100.000000
1992  40.107094  2922.391028  67.415723  122.888396  ...  100.000000
1993  40.463346  2931.150717  67.685917  122.890874  ...  100.000000
1994  40.567215  2939.949699  67.625220  122.879098  ...  100.000000

           XMV4  XMV5        XMV6       XMV7       XMV8  XMV9      XMV10  \
0     60.482854     0   24.229301  37.208198  46.430526     0  35.865322
1     60.524644     0   24.171763  37.227431  46.427192     0  35.719177
2     60.546193     0   25.179022  37.243766  46.442544     0  35.740715
3     60.568588     0   26.922729  37.211698  46.407497     0  35.736154
4     60.637598     0   29.039605  37.199517  46.424034     0  35.890716
...         ...   ...         ...        ...        ...   ...        ...
1990  57.399858     0  100.000000  41.244686  45.466296     0  30.171207
1991  57.365210     0  100.000000  41.463254  45.413515     0  30.066018
1992  57.415508     0  100.000000  41.700081  45.373462     0  30.117846
1993  57.280676     0  100.000000  41.954073  45.361655     0  29.900523
1994  57.142232     0  100.000000  42.228208  45.332390     0  29.754342

          XMV11  XMV12
0     12.930642    100
1     11.714423    100
2     10.734676    100
3     10.311783    100
4     11.181380    100
...         ...    ...
1990  22.898173    100
1991  26.035429    100
1992  25.214501    100
1993  25.175145    100
1994  23.803439    100

[1995 rows x 54 columns]

In [2]:
#print datatypes of each column
df.dtypes

Index        int64
XMEAS1     float64
XMEAS2     float64
XMEAS3     float64
XMEAS4     float64
XMEAS5     float64
XMEAS6     float64
XMEAS7     float64
XMEAS8     float64
XMEAS9     float64
XMEAS10    float64
XMEAS11    float64
XMEAS12    float64
XMEAS13    float64
XMEAS14    float64
XMEAS15    float64
XMEAS16    float64
XMEAS17    float64
XMEAS18    float64
XMEAS19    float64
XMEAS20    float64
XMEAS21    float64
XMEAS22    float64
XMEAS23    float64
XMEAS24    float64
XMEAS25    float64
XMEAS26    float64
XMEAS27    float64
XMEAS28    float64
XMEAS29    float64
XMEAS30    float64
XMEAS31    float64
XMEAS32    float64
XMEAS33    float64
XMEAS34    float64
XMEAS35    float64
XMEAS36    float64
XMEAS37    float64
XMEAS38    float64
XMEAS39    float64
XMEAS40    float64
XMEAS41    float64
XMV1       float64
XMV2       float64
XMV3       float64
XMV4       float64
XMV5         int64
XMV6       float64
XMV7       float64
XMV8       float64
XMV9         int64
XMV10      float64
XMV11      float64
XMV12        int64
dtype: object

In [3]:
#fill empty values with attribute mean
df = df.fillna(df.mean())
print(df)

      Index    XMEAS1       XMEAS2       XMEAS3    XMEAS4     XMEAS5  \
0         1  0.271033  3649.739415  4451.320791  9.223142  32.392900
1         2  0.270826  3653.341885  4488.640140  9.211980  32.501953
2         3  0.270474  3688.113265  4432.832766  9.235690  32.402838
3         4  0.272127  3651.680041  4459.268940  9.192009  31.876790
4         5  0.270939  3636.329271  4460.409756  9.277992  32.424754
...     ...       ...          ...          ...       ...        ...
1990   1991 -0.001158  3744.190299  4863.374473  8.792891  24.901362
1991   1992 -0.001147  3798.451896  4864.787808  8.814539  24.783557
1992   1993 -0.000370  3774.038558  4891.309364  8.659021  24.805757
1993   1994 -0.000925  3812.197101  4909.631048  8.724842  24.877275
1994   1995 -0.000317  3761.939300  4935.966769  8.746042  24.470426

         XMEAS6       XMEAS7     XMEAS8      XMEAS9  ...        XMV3  \
0     47.559754  2798.975799  64.995825  122.898796  ...   26.662173
1     47.374855  2800.296214  65.091251  122.877519  ...   26.689544
2     47.817088  2802.647777  64.812363  122.916165  ...   26.705507
3     47.869249  2803.693084  64.205417  122.892493  ...   26.768653
4     47.509322  2804.787223  64.598623  122.890514  ...   26.396773
...         ...          ...        ...         ...  ...         ...
1990  40.390117  2903.201084  66.243082  122.882878  ...  100.000000
1991  40.401312  2911.912112  68.055534  122.881328  ...  100.000000
1992  40.107094  2922.391028  67.415723  122.888396  ...  100.000000
1993  40.463346  2931.150717  67.685917  122.890874  ...  100.000000
1994  40.567215  2939.949699  67.625220  122.879098  ...  100.000000

           XMV4  XMV5        XMV6       XMV7       XMV8  XMV9      XMV10  \
0     60.482854     0   24.229301  37.208198  46.430526     0  35.865322
1     60.524644     0   24.171763  37.227431  46.427192     0  35.719177
2     60.546193     0   25.179022  37.243766  46.442544     0  35.740715
3     60.568588     0   26.922729  37.211698  46.407497     0  35.736154
4     60.637598     0   29.039605  37.199517  46.424034     0  35.890716
...         ...   ...         ...        ...        ...   ...        ...
1990  57.399858     0  100.000000  41.244686  45.466296     0  30.171207
1991  57.365210     0  100.000000  41.463254  45.413515     0  30.066018
1992  57.415508     0  100.000000  41.700081  45.373462     0  30.117846
1993  57.280676     0  100.000000  41.954073  45.361655     0  29.900523
1994  57.142232     0  100.000000  42.228208  45.332390     0  29.754342

          XMV11  XMV12
0     12.930642    100
1     11.714423    100
2     10.734676    100
3     10.311783    100
4     11.181380    100
...         ...    ...
1990  22.898173    100
1991  26.035429    100
1992  25.214501    100
1993  25.175145    100
1994  23.803439    100

[1995 rows x 54 columns]

In [4]:
import sklearn
from sklearn.model_selection import train_test_split as tts

y = df["XMEAS1"]
x = df.drop(columns = "XMEAS1")

print(y)
print(x)

0       0.271033
1       0.270826
2       0.270474
3       0.272127
4       0.270939
          ...
1990   -0.001158
1991   -0.001147
1992   -0.000370
1993   -0.000925
1994   -0.000317
Name: XMEAS1, Length: 1995, dtype: float64
      Index       XMEAS2       XMEAS3    XMEAS4     XMEAS5     XMEAS6  \
0         1  3649.739415  4451.320791  9.223142  32.392900  47.559754
1         2  3653.341885  4488.640140  9.211980  32.501953  47.374855
2         3  3688.113265  4432.832766  9.235690  32.402838  47.817088
3         4  3651.680041  4459.268940  9.192009  31.876790  47.869249
4         5  3636.329271  4460.409756  9.277992  32.424754  47.509322
...     ...          ...          ...       ...        ...        ...
1990   1991  3744.190299  4863.374473  8.792891  24.901362  40.390117
1991   1992  3798.451896  4864.787808  8.814539  24.783557  40.401312
1992   1993  3774.038558  4891.309364  8.659021  24.805757  40.107094
1993   1994  3812.197101  4909.631048  8.724842  24.877275  40.463346
1994   1995  3761.939300  4935.966769  8.746042  24.470426  40.567215

           XMEAS7     XMEAS8      XMEAS9   XMEAS10  ...        XMV3  \
0     2798.975799  64.995825  122.898796  0.197826  ...   26.662173
1     2800.296214  65.091251  122.877519  0.196092  ...   26.689544
2     2802.647777  64.812363  122.916165  0.204023  ...   26.705507
3     2803.693084  64.205417  122.892493  0.220561  ...   26.768653
4     2804.787223  64.598623  122.890514  0.236146  ...   26.396773
...           ...        ...         ...       ...  ...         ...
1990  2903.201084  66.243082  122.882878  0.648268  ...  100.000000
1991  2911.912112  68.055534  122.881328  0.646405  ...  100.000000
1992  2922.391028  67.415723  122.888396  0.641291  ...  100.000000
1993  2931.150717  67.685917  122.890874  0.645821  ...  100.000000
1994  2939.949699  67.625220  122.879098  0.644735  ...  100.000000

           XMV4  XMV5        XMV6       XMV7       XMV8  XMV9      XMV10  \
0     60.482854     0   24.229301  37.208198  46.430526     0  35.865322
1     60.524644     0   24.171763  37.227431  46.427192     0  35.719177
2     60.546193     0   25.179022  37.243766  46.442544     0  35.740715
3     60.568588     0   26.922729  37.211698  46.407497     0  35.736154
4     60.637598     0   29.039605  37.199517  46.424034     0  35.890716
...         ...   ...         ...        ...        ...   ...        ...
1990  57.399858     0  100.000000  41.244686  45.466296     0  30.171207
1991  57.365210     0  100.000000  41.463254  45.413515     0  30.066018
1992  57.415508     0  100.000000  41.700081  45.373462     0  30.117846
1993  57.280676     0  100.000000  41.954073  45.361655     0  29.900523
1994  57.142232     0  100.000000  42.228208  45.332390     0  29.754342

          XMV11  XMV12
0     12.930642    100
1     11.714423    100
2     10.734676    100
3     10.311783    100
4     11.181380    100
...         ...    ...
1990  22.898173    100
1991  26.035429    100
1992  25.214501    100
1993  25.175145    100
1994  23.803439    100

[1995 rows x 53 columns]

In [5]:
x_train, x_test, y_train, y_test = tts(x, y, test_size=0.2, random_state=42)

In [6]:
traindf = pd.DataFrame(x_train, y_train)
traindf = df.drop(columns ="Index")
print(traindf)

        XMEAS1       XMEAS2       XMEAS3    XMEAS4     XMEAS5     XMEAS6  \
0     0.271033  3649.739415  4451.320791  9.223142  32.392900  47.559754
1     0.270826  3653.341885  4488.640140  9.211980  32.501953  47.374855
2     0.270474  3688.113265  4432.832766  9.235690  32.402838  47.817088
3     0.272127  3651.680041  4459.268940  9.192009  31.876790  47.869249
4     0.270939  3636.329271  4460.409756  9.277992  32.424754  47.509322
...        ...          ...          ...       ...        ...        ...
1990 -0.001158  3744.190299  4863.374473  8.792891  24.901362  40.390117
1991 -0.001147  3798.451896  4864.787808  8.814539  24.783557  40.401312
1992 -0.000370  3774.038558  4891.309364  8.659021  24.805757  40.107094
1993 -0.000925  3812.197101  4909.631048  8.724842  24.877275  40.463346
1994 -0.000317  3761.939300  4935.966769  8.746042  24.470426  40.567215

           XMEAS7     XMEAS8      XMEAS9   XMEAS10  ...        XMV3  \
0     2798.975799  64.995825  122.898796  0.197826  ...   26.662173
1     2800.296214  65.091251  122.877519  0.196092  ...   26.689544
2     2802.647777  64.812363  122.916165  0.204023  ...   26.705507
3     2803.693084  64.205417  122.892493  0.220561  ...   26.768653
4     2804.787223  64.598623  122.890514  0.236146  ...   26.396773
...           ...        ...         ...       ...  ...         ...
1990  2903.201084  66.243082  122.882878  0.648268  ...  100.000000
1991  2911.912112  68.055534  122.881328  0.646405  ...  100.000000
1992  2922.391028  67.415723  122.888396  0.641291  ...  100.000000
1993  2931.150717  67.685917  122.890874  0.645821  ...  100.000000
1994  2939.949699  67.625220  122.879098  0.644735  ...  100.000000

           XMV4  XMV5        XMV6       XMV7       XMV8  XMV9      XMV10  \
0     60.482854     0   24.229301  37.208198  46.430526     0  35.865322
1     60.524644     0   24.171763  37.227431  46.427192     0  35.719177
2     60.546193     0   25.179022  37.243766  46.442544     0  35.740715
3     60.568588     0   26.922729  37.211698  46.407497     0  35.736154
4     60.637598     0   29.039605  37.199517  46.424034     0  35.890716
...         ...   ...         ...        ...        ...   ...        ...
1990  57.399858     0  100.000000  41.244686  45.466296     0  30.171207
1991  57.365210     0  100.000000  41.463254  45.413515     0  30.066018
1992  57.415508     0  100.000000  41.700081  45.373462     0  30.117846
1993  57.280676     0  100.000000  41.954073  45.361655     0  29.900523
1994  57.142232     0  100.000000  42.228208  45.332390     0  29.754342

          XMV11  XMV12
0     12.930642    100
1     11.714423    100
2     10.734676    100
3     10.311783    100
4     11.181380    100
...         ...    ...
1990  22.898173    100
1991  26.035429    100
1992  25.214501    100
1993  25.175145    100
1994  23.803439    100

[1995 rows x 53 columns]

In [7]:
#scale data to be centered around 0
centered_df = traindf.apply(lambda V1: V1-V1.mean())
print(centered_df)

        XMEAS1      XMEAS2      XMEAS3    XMEAS4    XMEAS5    XMEAS6  \
0     0.009944  -12.828985   -9.323455 -0.042837  0.188510  0.125685
1     0.009737   -9.226515   27.995894 -0.053999  0.297563 -0.059214
2     0.009385   25.544865  -27.811480 -0.030289  0.198448  0.383020
3     0.011038  -10.888359   -1.375306 -0.073970 -0.327600  0.435180
4     0.009850  -26.239129   -0.234490  0.012013  0.220365  0.075254
...        ...         ...         ...       ...       ...       ...
1990 -0.262247   81.621899  402.730227 -0.473088 -7.303027 -7.043952
1991 -0.262236  135.883496  404.143562 -0.451440 -7.420832 -7.032757
1992 -0.261460  111.470158  430.665118 -0.606958 -7.398633 -7.326974
1993 -0.262014  149.628701  448.986802 -0.541137 -7.327114 -6.970722
1994 -0.261406   99.370900  475.322523 -0.519937 -7.733963 -6.866853

          XMEAS7    XMEAS8    XMEAS9   XMEAS10  ...       XMV3      XMV4  \
0       8.702112  0.003035 -0.000389 -0.068703  ...  -2.478659 -0.279842
1      10.022527  0.098462 -0.021667 -0.070437  ...  -2.451288 -0.238052
2      12.374090 -0.180426  0.016980 -0.062506  ...  -2.435325 -0.216503
3      13.419397 -0.787372 -0.006692 -0.045968  ...  -2.372179 -0.194108
4      14.513536 -0.394166 -0.008672 -0.030383  ...  -2.744059 -0.125099
...          ...       ...       ...       ...  ...        ...       ...
1990  112.927397  1.250293 -0.016307  0.381739  ...  70.859168 -3.362839
1991  121.638425  3.062745 -0.017858  0.379876  ...  70.859168 -3.397486
1992  132.117341  2.422934 -0.010790  0.374762  ...  70.859168 -3.347188
1993  140.877030  2.693128 -0.008312  0.379292  ...  70.859168 -3.482020
1994  149.676012  2.632431 -0.020087  0.378206  ...  70.859168 -3.620465

      XMV5       XMV6      XMV7      XMV8  XMV9     XMV10      XMV11  XMV12
0      0.0  -8.774126  0.013905  0.044273   0.0 -0.081318   0.437228    0.0
1      0.0  -8.831665  0.033138  0.040939   0.0 -0.227462  -0.778992    0.0
2      0.0  -7.824405  0.049473  0.056291   0.0 -0.205924  -1.758739    0.0
3      0.0  -6.080698  0.017405  0.021244   0.0 -0.210485  -2.181632    0.0
4      0.0  -3.963822  0.005225  0.037781   0.0 -0.055924  -1.312034    0.0
...    ...        ...       ...       ...   ...       ...        ...    ...
1990   0.0  66.996573  4.050393 -0.919957   0.0 -5.775432  10.404758    0.0
1991   0.0  66.996573  4.268961 -0.972739   0.0 -5.880621  13.542015    0.0
1992   0.0  66.996573  4.505788 -1.012791   0.0 -5.828793  12.721087    0.0
1993   0.0  66.996573  4.759780 -1.024598   0.0 -6.046116  12.681730    0.0
1994   0.0  66.996573  5.033915 -1.053863   0.0 -6.192297  11.310024    0.0

[1995 rows x 53 columns]

In [8]:
from sklearn import preprocessing

#normalize all data to be between 0 and 1
min_max_scaler = preprocessing.MinMaxScaler()
scaled_df = pd.DataFrame(min_max_scaler.fit_transform(centered_df))
scaled_df.columns = ['XMEAS1', 'XMEAS2', 'XMEAS3', 'XMEAS4', 'XMEAS5', 'XMEAS6', 'XMEAS7', 'XMEAS8', 'XMEAS9', 'XMEAS10', 'XMEAS11', 'XMEAS12', 'XMEAS13', 'XMEAS14', 'XMEAS15', 'XMEAS16', 'XMEAS17', 'XMEAS18', 'XMEAS19', 'XMEAS20', 'XMEAS21', 'XMEAS22', 'XMEAS23', 'XMEAS24', 'XMEAS25', 'XMEAS26', 'XMEAS27', 'XMEAS28', 'XMEAS29', 'XMEAS30', 'XMEAS31', 'XMEAS32', 'XMEAS33', 'XMEAS34', 'XMEAS35', 'XMEAS36', 'XMEAS37', 'XMEAS38', 'XMEAS39', 'XMEAS40', 'XMEAS41', 'XMV1', 'XMV2', 'XMV3', 'XMV4', 'XMV5', 'XMV6', 'XMV7', 'XMV8', 'XMV9', 'XMV10', 'XMV11', 'XMV12']
print(scaled_df)

        XMEAS1    XMEAS2    XMEAS3    XMEAS4    XMEAS5    XMEAS6    XMEAS7  \
0     0.350968  0.292521  0.238525  0.468659  0.777944  0.757940  0.516965
1     0.350702  0.308210  0.297161  0.459386  0.788652  0.739205  0.521489
2     0.350251  0.459634  0.209477  0.479083  0.778920  0.784015  0.529546
3     0.352372  0.300972  0.251013  0.442794  0.727265  0.789300  0.533128
4     0.350848  0.234122  0.252805  0.514226  0.781072  0.752830  0.536877
...        ...       ...       ...       ...       ...       ...       ...
1990  0.001804  0.703841  0.885943  0.111216  0.042316  0.031476  0.874084
1991  0.001818  0.940142  0.888164  0.129201  0.030748  0.032611  0.903932
1992  0.002814  0.833825  0.929834  0.000000  0.032928  0.002799  0.939837
1993  0.002103  1.000000  0.958621  0.054682  0.039950  0.038896  0.969851
1994  0.002882  0.781135  1.000000  0.072295  0.000000  0.049421  1.000000

        XMEAS8    XMEAS9   XMEAS10  ...      XMV3      XMV4  XMV5      XMV6  \
0     0.493909  0.450876  0.240103  ...  0.266622  0.464588   0.0  0.241389
1     0.509693  0.256541  0.238025  ...  0.266895  0.470400   0.0  0.240813
2     0.463563  0.609511  0.247526  ...  0.267055  0.473396   0.0  0.250898
3     0.363171  0.393308  0.267338  ...  0.267687  0.476511   0.0  0.268356
4     0.428209  0.375228  0.286009  ...  0.263968  0.486108   0.0  0.289550
...        ...       ...       ...  ...       ...       ...   ...       ...
1990  0.700211  0.305489  0.779715  ...  1.000000  0.035829   0.0  1.000000
1991  1.000000  0.291328  0.777484  ...  1.000000  0.031010   0.0  1.000000
1992  0.894172  0.355883  0.771357  ...  1.000000  0.038005   0.0  1.000000
1993  0.938863  0.378516  0.776784  ...  1.000000  0.019254   0.0  1.000000
1994  0.928824  0.270966  0.775484  ...  1.000000  0.000000   0.0  1.000000

          XMV7      XMV8  XMV9     XMV10     XMV11  XMV12
0     0.277760  0.580246   0.0  0.788559  0.310381    0.0
1     0.280527  0.578484   0.0  0.769701  0.246380    0.0
2     0.282877  0.586596   0.0  0.772480  0.194822    0.0
3     0.278263  0.568077   0.0  0.771891  0.172568    0.0
4     0.276511  0.576815   0.0  0.791836  0.218329    0.0
...        ...       ...   ...       ...       ...    ...
1990  0.858498  0.070755   0.0  0.053792  0.834907    0.0
1991  0.889944  0.042866   0.0  0.040219  1.000000    0.0
1992  0.924017  0.021702   0.0  0.046906  0.956800    0.0
1993  0.960560  0.015464   0.0  0.018863  0.954729    0.0
1994  1.000000  0.000000   0.0  0.000000  0.882545    0.0

[1995 rows x 53 columns]